package scout

import "testing"

func TestIgnorerBuiltins(t *testing.T) {
	ig, err := LoadIgnorer(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range []string{"vendor/x/y.go", "internal/testdata/f.go", "a/node_modules/b.js", "x/api.pb.go", ".git/HEAD"} {
		if !ig.Skip(p) {
			t.Errorf("%s should be skipped", p)
		}
	}
	if ig.Skip("cmd/bd/main.go") {
		t.Error("real file skipped")
	}
	if !IsGenerated([]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x")) {
		t.Error("generated header not detected")
	}
}

func TestIgnorerFile(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, root, ".beads/codemap-ignore", "# comment\nwebsite/\n*.min.js\n")
	ig, _ := LoadIgnorer(root)
	if !ig.Skip("website/index.html") || !ig.Skip("static/app.min.js") || ig.Skip("static/app.js") {
		t.Error("codemap-ignore patterns not honoured")
	}
}
