//go:build cgo

package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/steveyegge/beads/internal/codemap/cache"
)

// runCodemap runs "bd codemap ..." in dir and returns stdout, failing the test
// on a non-zero exit. It is the embedded-CLI harness every other cmd/bd
// integration test uses (exec the built binary with bdEnv), not an in-process
// rootCmd call: the code map's writes go through the embedded Dolt store, and
// only a subprocess gets the auto-commit epilogue main.go runs on exit.
func runCodemap(t *testing.T, bd, dir string, args ...string) string {
	t.Helper()
	out, stderr, err := runBDRaw(t, bd, dir, append([]string{"codemap"}, args...)...)
	if err != nil {
		t.Fatalf("bd codemap %s failed: %v\nstdout:\n%s\nstderr:\n%s", strings.Join(args, " "), err, out, stderr)
	}
	return out
}

// runCodemapErr is runCodemap for the paths that are SUPPOSED to fail; it
// returns combined output and the exit error.
func runCodemapErr(t *testing.T, bd, dir string, args ...string) (string, error) {
	t.Helper()
	out, stderr, err := runBDRaw(t, bd, dir, append([]string{"codemap"}, args...)...)
	return out + stderr, err
}

func runBDRaw(t *testing.T, bd, dir string, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	cmd := exec.Command(bd, args...)
	cmd.Dir = dir
	cmd.Env = bdEnv(dir)
	so, se, err := runCommandBuffers(t, cmd)
	return so.String(), se.String(), err
}

// runBDStdin runs bd with stdin wired to the given string and returns stdout.
// The agent tool hooks read their whole payload from stdin, so exercising them
// through the same built-binary harness needs this one extra wire.
func runBDStdin(t *testing.T, bd, dir, stdin string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command(bd, args...)
	cmd.Dir = dir
	cmd.Env = bdEnv(dir)
	cmd.Stdin = strings.NewReader(stdin)
	so, se, err := runCommandBuffers(t, cmd)
	if err != nil {
		return so.String() + se.String(), err
	}
	return so.String(), nil
}

// runBDEnvRaw is runBDRaw with a caller-supplied environment, for the hook
// paths whose whole behavior is an env var.
func runBDEnvRaw(t *testing.T, bd, dir string, env []string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command(bd, args...)
	cmd.Dir = dir
	cmd.Env = env
	so, se, err := runCommandBuffers(t, cmd)
	return so.String() + se.String(), err
}

// mustCodemapJSON decodes the first JSON object in out into v.
func mustCodemapJSON(t *testing.T, out string, v any) {
	t.Helper()
	start := strings.Index(out, "{")
	if start < 0 {
		t.Fatalf("no JSON object in output: %s", out)
	}
	if err := json.Unmarshal([]byte(out[start:]), v); err != nil {
		t.Fatalf("decoding %s: %v", out[start:], err)
	}
}

// goMiniFiles is the same fixture as internal/codemap/scout/testdata/go-mini:
// two packages, one import between them, one external test, plus a generated
// file and a vendored file the scout must ignore.
var goMiniFiles = map[string]string{
	"go.mod":        "module example.com/mini\n\ngo 1.21\n",
	"a/a.go":        "package a\n\nfunc A() {}\n\nfunc B() {}\n",
	"b/b.go":        "package b\n\nimport (\n\t\"fmt\"\n\n\t\"example.com/mini/a\"\n)\n\nfunc Run() { fmt.Println(a.A) }\n",
	"b/b_test.go":   "package b_test\n\nimport (\n\t\"testing\"\n\n\t\"example.com/mini/b\"\n)\n\nfunc TestRun(t *testing.T) { b.Run() }\n",
	"gen/gen.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage gen\n\nfunc Generated() {}\n",
	"vendor/v/v.go": "package v\n\nfunc V() {}\n",
}

// writeGoMini writes the fixture into dir and commits it. The files are STAGED
// explicitly rather than with `git add -A`: scout.BlobHashes reads
// `git ls-files -s`, so an unstaged file would index with an empty blob hash,
// and a blanket add would sweep in whatever bd init left under .beads.
func writeGoMini(t *testing.T, dir string) {
	t.Helper()
	for rel, body := range goMiniFiles {
		writeRepoFile(t, dir, rel, body)
	}
	paths := make([]string, 0, len(goMiniFiles))
	for rel := range goMiniFiles {
		paths = append(paths, rel)
	}
	gitAdd(t, dir, paths...)
	gitCommit(t, dir, "go-mini fixture")
}

func writeRepoFile(t *testing.T, dir, rel, body string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// appendFile appends to a repo file, creating it if absent.
func appendFile(t *testing.T, dir, rel, body string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(rel))
	// #nosec G304 -- test-controlled path under t.TempDir()
	f, err := os.OpenFile(full, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.WriteString(body); err != nil {
		f.Close()
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
}

func gitAdd(t *testing.T, dir string, paths ...string) {
	t.Helper()
	cmd := exec.Command("git", append([]string{"add", "--"}, paths...)...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git add: %v\n%s", err, out)
	}
}

func gitCommit(t *testing.T, dir, msg string) string {
	t.Helper()
	cmd := exec.Command("git", "commit", "-q", "--no-verify", "-m", msg)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git commit: %v\n%s", err, out)
	}
	rev := exec.Command("git", "rev-parse", "HEAD")
	rev.Dir = dir
	out, err := rev.Output()
	if err != nil {
		t.Fatalf("git rev-parse: %v", err)
	}
	return strings.TrimSpace(string(out))
}

// gitCommitAll stages the named paths and commits them.
func gitCommitAll(t *testing.T, dir, msg string, paths ...string) string {
	t.Helper()
	gitAdd(t, dir, paths...)
	return gitCommit(t, dir, msg)
}

// createIssue runs "bd create --json" and returns the new issue's id.
func createIssue(t *testing.T, bd, dir, title string) string {
	t.Helper()
	stdout, stderr, err := runBDRaw(t, bd, dir, "create", "--json", title)
	if err != nil {
		t.Fatalf("bd create failed: %v\nstdout:\n%s\nstderr:\n%s", err, stdout, stderr)
	}
	var issue struct {
		ID string `json:"id"`
	}
	mustCodemapJSON(t, stdout, &issue)
	if issue.ID == "" {
		t.Fatalf("bd create returned no id: %s", stdout)
	}
	return issue.ID
}

// gitRm removes a tracked path and stages the removal.
func gitRm(t *testing.T, dir, path string) {
	t.Helper()
	cmd := exec.Command("git", "rm", "-rq", "--", path)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git rm %s: %v\n%s", path, err, out)
	}
}

// readCodemapCache decodes the derived cache the codemap verbs write.
func readCodemapCache(t *testing.T, beadsDir string) cache.File {
	t.Helper()
	f, err := cache.Read(beadsDir)
	if err != nil {
		t.Fatalf("reading code map cache: %v", err)
	}
	return f
}

func containsString(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}
