package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/steveyegge/beads/internal/beads"
)

// docsInitCmd scaffolds the wiki dir + wires the post-close hook. Idempotent:
// never resets an existing .docs-state, never rewrites an existing README,
// never duplicates the hook block.
var docsInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold the wiki + wire the post-close hook (idempotent)",
	Args:  cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		repoRoot := findRepoRootForArch()
		if repoRoot == "" {
			FatalErrorRespectJSON("not in a git repository (bd docs init needs a repo root)")
		}
		if err := runDocsInit(repoRoot, docsDirName()); err != nil {
			FatalErrorRespectJSON("bd docs init: %v", err)
		}
	},
}

// runDocsInit is the testable core behind docsInitCmd.
func runDocsInit(repoRoot, docsDir string) error {
	logDir := filepath.Join(repoRoot, docsDir, "log")
	if err := os.MkdirAll(logDir, 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", logDir, err)
	}

	statePath := docsStatePath(repoRoot, docsDir)
	stateCreated := false
	if _, ok := readDocsState(statePath); !ok {
		st := docsState{RegenWatermark: time.Now().UTC()}
		if err := writeDocsState(statePath, st); err != nil {
			return fmt.Errorf("writing %s: %w", statePath, err)
		}
		stateCreated = true
	}

	readmePath := filepath.Join(repoRoot, docsDir, "README.md")
	readmeCreated := false
	if _, err := os.Stat(readmePath); err != nil {
		if err := os.WriteFile(readmePath, []byte(docsReadmeTemplate), 0o644); err != nil { // #nosec G306 -- README is documentation, meant to be world-readable.
			return fmt.Errorf("writing %s: %w", readmePath, err)
		}
		readmeCreated = true
	}

	hookCreated, hookWired, err := wireDocsHook(repoRoot)
	if err != nil {
		return fmt.Errorf("wiring post-close hook: %w", err)
	}

	summary := []string{stateSummary(stateCreated), readmeSummary(readmeCreated), hookSummary(hookCreated, hookWired)}
	fmt.Printf("bd docs init: %s\n", strings.Join(summary, ", "))
	return nil
}

func stateSummary(created bool) string {
	if created {
		return "state created"
	}
	return "state already present"
}

func readmeSummary(created bool) string {
	if created {
		return "README created"
	}
	return "README already present"
}

func hookSummary(created, wired bool) string {
	switch {
	case created:
		return "hook created"
	case wired:
		return "hook block added"
	default:
		return "hook already wired"
	}
}

// wireDocsHook ensures .beads/hooks/post-close exists and contains the docs
// block, without duplicating it (existence check on "bd docs update").
//
// If a hook already exists (e.g. seeded by 'bd arch init') and ends in an
// "exit 0" line, the block is spliced in BEFORE that line: sh's exit
// terminates the script immediately, so appending after it would be dead code.
func wireDocsHook(repoRoot string) (created, wired bool, err error) {
	bd := beads.FindBeadsDir()
	hooksDir := filepath.Join(bd, "hooks")
	if bd == "" {
		hooksDir = filepath.Join(repoRoot, ".beads", "hooks")
	}
	hookPath := filepath.Join(hooksDir, "post-close")

	data, statErr := os.ReadFile(hookPath) // #nosec G304 -- hookPath is <repoRoot|BEADS_DIR>/hooks/post-close, constructed by us.
	if statErr != nil {
		if err := os.MkdirAll(hooksDir, 0o750); err != nil {
			return false, false, err
		}
		if err := os.WriteFile(hookPath, []byte(docsHookBaseTemplate), 0o755); err != nil { // #nosec G306 -- hook must be executable.
			return false, false, err
		}
		return true, true, nil
	}

	content := string(data)
	if strings.Contains(content, docsHookMarker) {
		return false, false, nil // already wired
	}
	if idx := strings.LastIndex(content, "\nexit 0"); idx >= 0 {
		content = content[:idx] + "\n" + docsHookBlock + content[idx:]
	} else {
		content += docsHookBlock
	}
	if err := os.WriteFile(hookPath, []byte(content), 0o755); err != nil { // #nosec G306 -- hook must be executable.
		return false, false, err
	}
	return false, true, nil
}

// docsReadmeTemplate is the scaffolded <docsDir>/README.md placeholder.
const docsReadmeTemplate = `# Repo wiki

Living documentation maintained by ` + "`bd docs`" + ` (see ` + "`bd docs --help`" + `).
Narrative pages are regenerated by ` + "`bd docs regen`" + `; the log/ subdirectory
holds per-issue entries recorded automatically on ` + "`bd close`" + `.
`

// docsHookMarker is the exact managed-block marker line (F5): wiring
// detection greps for this, not the looser "bd docs update" substring, so a
// stray comment mentioning that phrase elsewhere in the hook doesn't count
// as already-wired.
const docsHookMarker = "# --- bd docs Tier 1 (managed"

// docsHookBlock is the idempotent marker block appended to
// .beads/hooks/post-close. docsHookMarker is the existence marker checked
// before appending (never duplicated).
//
// Only BD_NO_DOCS gates the call (F3): BD_DOCS_RUNNING must still let entries
// get written during a headless regen (--exec) — it only suppresses the
// regen nudge, inside 'bd docs update' itself, not the hook's decision to
// call it at all.
const docsHookBlock = `
# --- bd docs Tier 1 (managed; see 'bd docs --help') ---
if [ "${BD_NO_DOCS:-0}" != "1" ] && command -v bd >/dev/null 2>&1; then
  bd docs update "$@" || true
fi
# --- end bd docs Tier 1 ---
`

// docsHookBaseTemplate is written only when no post-close hook exists yet
// (e.g. 'bd arch init' hasn't run). POSIX sh only — no pipefail (dash kills
// it at startup; see arch.go's postCloseHookTemplate history).
const docsHookBaseTemplate = `#!/usr/bin/env sh
# .beads/hooks/post-close — scaffolded by 'bd docs init'. Advisory only:
# fires after 'bd close' succeeds and CANNOT block or undo the close.
# Args: $@ = closed issue IDs. cwd = repo root.
set -eu
` + docsHookBlock + `
exit 0
`

func init() {
	docsCmd.AddCommand(docsInitCmd)
}
